[htmls]
# Category names followed by optional flags: a1 a0 cim cof
analsex a1
anal_natur_no_condom a1 a0
gesichtsbesamung_cum_on_face cof
mundvollendung_cum_in_mouth cim

[variables]
# Variable assignments
GalsinPage=23
html0=https://booksusi.com/service/
html2=/?&city=wien&page=
arg4i=--domain=images.booksusi.com 
N=+15
